# Basic Site Settings
locale                   : "en-US"
site_theme               : "default" # The available themes options are "default", "air", "sunrise", "mint", "dirt" and "contrast"
title                    : "Junteng Liu - Personal Website"
title_separator          : "-"
name                     : &name "Junteng Liu"
description              : &description "First-year PhD candidate at HKUST NLP Group researching natural language processing and machine learning"   # Update this with a general description of your site, this is the default if not overridden by a page
url                      : https://LengthDragon.github.io/LJT-Homepage # The base hostname & protocol for your site e.g. "https://[your GitHub username].github.io",
                                                           # or if you already have some other page hosted on Github then use "https://[your GitHub username].github.io/[Your Repo Name]"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "LengthDragon/LJT-Homepage"